name: WinGet Releaser
description: Publish new releases of your application to Windows Package Manager easily.
inputs:
  identifier:
    required: true
    description: The PackageIdentifier of the package you want to release.
  version:
    required: false
    description: The PackageVersion of the package you want to release.
  installers-regex:
    required: true
    description: The regex to match the installers.
    default: '.(exe|msi|msix|appx)(bundle){0,1}$'
  delete-previous-version:
    required: true
    description: Whether to delete the last version.
    default: 'false'
  release-repository:
    required: false # true
    description: The repository where the release is present (should be present under same user/organization).
    # since `schedule` event doesn't have any event payload,
    # we need to get current repository name from `context.repo.repo` in index.js
    # default: ${{ github.event.repository.name }}
  release-tag:
    required: true
    description: The release tag to be used for creating manifests.
    default: ${{ github.release.tag_name || github.ref_name }}
  token:
    required: true
    description: GitHub token to create pull request on Windows Package Manager Community Repository.
  fork-user:
    required: true
    description: GitHub username where the fork of winget-pkgs is present.
    default: ${{ github.repository_owner }}
runs:
  using: node16
  main: dist/index.js
branding:
  color: blue
  icon: upload-cloud
